# Generated by Django 4.1.1 on 2023-12-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vegetable", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Recipe_name", models.CharField(max_length=20)),
                ("Recipe_discription", models.TextField()),
                ("Recipe_image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.DeleteModel(name="Student",),
    ]
