# Generated by Django 4.1.1 on 2023-12-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("Recipe_id", models.AutoField(primary_key=True, serialize=False)),
                ("Recipe_name", models.CharField(max_length=20)),
                ("Recipe_discription", models.TextField()),
                ("Recipe_image", models.ImageField(upload_to="Recipe")),
            ],
        ),
    ]
